### PR TITLE
Add Chinese (Traditional) translate

### PR DESCRIPTION
**Pull request by hugwalk**
aka zh_rTW

### CODE REVIEW

**Comment by paphonb** [comment]
Please fix formatting errors.

**Comment by hugwalk** [comment]
Can you please point out where the errors are?

**Comment by paphonb** [comment]
Click details in this section. It will show what caused the errors.
image

**Comment by paphonb** [comment]
Umm you removed the original strings file. Can you fork the project again and copy the new folder that you added?

Thanks.

**Pull request closed without merging**
